<a href="https://colab.research.google.com/github/raulmabcn/DataAnalyst/blob/main/Foundations/Python/Exercices/Bloque1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###1️⃣ Udemy – Análisis combinado

Muestra los cursos cuyo rating sea superior a la media de su propia categoría.

Obtén el curso con más subscribers de cada instructional_level.

Calcula el porcentaje de cursos gratuitos (is_paid = False) por categoría.

Muestra las categorías donde la mediana de reviews sea superior a 10.000.

In [60]:
import pandas as pd
data = pd.read_csv('udemy_courses.csv')
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3691 entries, 0 to 3690
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   3691 non-null   int64
 1   title                3691 non-null   object
 2   url                  3691 non-null   object
 3   is_paid              3691 non-null   bool
 4   instructor_names     3691 non-null   object
 5   category             3691 non-null   object
 6   headline             3691 non-null   object
 7   num_subscribers      3691 non-null   int64
 8   rating               3691 non-null   float64
 9   num_reviews          3691 non-null   int64
 10  instructional_level  3691 non-null   object
 11  objectives           3691 non-null   object
 12  curriculum           3691 non-null   object
dtypes: bool(1), float64(1), int64(3), object(8)
memory usage: 349.8+ KB
None

In [61]:
print( data[ data['rating'] > data.groupby('category')['rating'].transform('mean')][['category', 'title', 'rating']] )

#category_mean = ( data.groupby('category', as_index = False ).agg( category_mean = ('rating','mean')))
#data_merge = data.merge(category_mean, on = 'category')
#print( data_merge[data_merge['rating'] > data_merge['category_mean']][['category','title','rating','category_mean']] )

         category                                              title    rating
0     Development  The Complete Python Bootcamp From Zero to Hero...  4.576494
1     Development         The Complete 2024 Web Development Bootcamp  4.679065
2     Development  100 Days of Code: The Complete Python Pro Boot...  4.698768
3     Development                    The Web Developer Bootcamp 2024  4.673450
4     Development  React - The Complete Guide 2024 (incl. Next.js...  4.638643
...           ...                                                ...       ...
3672  Development  Python Programming for Beginners | Full Course...  4.472529
3673  Development  Computer Vision with OpenCV Python | Official ...  4.714398
3687  Development  Advanced WordPress & Elementor 2024 | Build Dy...  4.682569
3688  Development    Web Design Course for Beginners to Intermediate  4.540056
3689  Development  D3.js in Action: Build 17 D3.js Data Visualiza...  4.438985

[2260 rows x 3 columns]

In [62]:
print( data[ data['num_subscribers'] ==  data.groupby('instructional_level')['num_subscribers'].transform('max')][['instructional_level','title','num_subscribers']])
#idx = data.groupby('instructional_level')['num_subscribers'].idxmax()
#print( data.loc[idx][['category','title','rating']] )

     instructional_level                                              title  \
0             All Levels  The Complete Python Bootcamp From Zero to Hero...
16        Beginner Level  The Ultimate MySQL Bootcamp: Go from SQL Begin...
1574  Intermediate Level  Learn Machine learning & AI [Beginner to advan...
2024        Expert Level                          Flutter - Advanced Course

      num_subscribers
0             1976866
16             466263
1574           270974
2024            96155

In [63]:
data_paid = (~data['is_paid']).groupby(data['category']).mean() * 100
print(data_paid)

category
Development    0.0
Name: is_paid, dtype: float64

In [64]:
data_category = data.groupby('category')['num_reviews'].median()
print( data_category[ data_category > 100 ] )
#data_category = data.groupby('category', as_index = False)['num_reviews'].median()
#print( data_category[ data_category['num_reviews'] > 100 ] )

category
Development    966.0
Name: num_reviews, dtype: float64

###2️⃣ Hospitals – Filtros y métricas derivadas

Calcula una nueva columna ratio_pacientes_por_cama = total_pacientes / num_camas
(suponiendo que debes calcular primero los pacientes por hospital desde pacientes.csv).

Muestra los hospitales cuyo indice_satisfaccion esté por encima de la media de su comunidad autónoma.

Encuentra las provincias donde todos los hospitales tienen ocupación superior al 60%.

Muestra las comunidades autónomas donde el hospital con más camas tenga también un índice de satisfacción inferior a la media nacional.

In [68]:
data_h = pd.read_csv('hospitals.csv', sep=';', encoding='latin-1')
data_p = pd.read_csv('pacientes.csv', sep=';', encoding='latin-1')
data_h.info()
data_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   hospital_id                 170 non-null    int64
 1   nombre                      170 non-null    object
 2   localidad                   170 non-null    object
 3   provincia                   170 non-null    object
 4   comunidad_autonoma          170 non-null    object
 5   presupuesto_anual_millones  170 non-null    float64
 6   num_camas                   170 non-null    int64
 7   num_medicos                 170 non-null    int64
 8   indice_satisfaccion         170 non-null    float64
 9   porcentaje_ocupacion        170 non-null    float64
dtypes: float64(3), int64(3), object(4)
memory usage: 13.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5060 entries, 0 to 5059
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   paciente_id          5060 non-null   int64
 1   nombre               5060 non-null   object
 2   hospital_id          5060 non-null   int64
 3   edad                 5060 non-null   int64
 4   nacionalidad         5060 non-null   object
 5   numero_visitas       5060 non-null   int64
 6   ingreso              5060 non-null   object
 7   numero_dias_ingreso  5060 non-null   int64
dtypes: int64(5), object(3)
memory usage: 316.4+ KB

In [67]:
data_p_h = data_p.groupby('hospital_id', as_index=False)['paciente_id'].count().rename(columns={'paciente_id':'total_pacientes'})
data_h_p = data_h.merge( data_p_h, on ='hospital_id' )
data_h['ratio_pacietes_por_cama'] = data_h_p['total_pacientes']/data_h_p['num_camas']
data_h

,hospital_id,nombre,localidad,provincia,comunidad_autonoma,presupuesto_anual_millones,num_camas,num_medicos,indice_satisfaccion,porcentaje_ocupacion,ratio_pacietes_por_cama
0,1,Hospital Universitario Torrecardenas,Almeria,Almeria,Andalucia,138.92,645,329,9.5,96.8,0.051163
1,2,Hospital de Poniente,Almeria,Almeria,Andalucia,150.52,575,228,4.2,78.5,0.057391
2,3,Hospital Universitario Puerta del Mar,Cadiz,Cadiz,Andalucia,496.80,834,32,6.4,81.5,0.044365
3,4,Hospital de Jerez,Jerez de la Frontera,Cadiz,Andalucia,149.66,773,56,5.8,50.7,0.042691
4,5,Hospital Universitario Reina Sofia,Cordoba,Cordoba,Andalucia,358.41,277,433,1.9,61.4,0.097473
...,...,...,...,...,...,...,...,...,...,...,...
165,166,Hospital San Pedro,Logroño,La Rioja,La Rioja,457.88,944,104,3.4,89.4,0.038136
166,167,Hospital Universitario de Ceuta,Ceuta,Ceuta,Ceuta,263.46,208,276,6.3,88.5,0.163462
167,168,Hospital Comarcal de Melilla,Melilla,Melilla,Melilla,384.25,652,127,6.5,88.4,0.072086
168,169,Fundacion Hospital Calahorra,Calahorra,La Rioja,La Rioja,54.92,126,182,2.3,54.8,0.333333
169,170,Hospital General de La Rioja,Logroño,La Rioja,La Rioja,83.10,517,112,3.6,65.5,0.059961

In [66]:
data_h[data_h['indice_satisfaccion'] > data_h.groupby('comunidad_autonoma')['indice_satisfaccion'].transform('mean') ]['nombre']

0           Hospital Universitario Torrecardenas
2          Hospital Universitario Puerta del Mar
3                              Hospital de Jerez
8      Hospital Universitario Juan Ramon Jimenez
10                Hospital Universitario de Jaen
                         ...
161               Hospital Universitario Basurto
162                     Hospital de Santa Marina
164                            Hospital San Eloy
165                           Hospital San Pedro
169                 Hospital General de La Rioja
Name: nombre, Length: 86, dtype: object

In [80]:
#( data_h['porcentaje_ocupacion'] > 60 ).groupby(data_h['provincia']).mean() == 1.0
provincias_validas = ( data_h['porcentaje_ocupacion'] > 60 ).groupby(data_h['provincia']).all()
provincias_validas[provincias_validas]

provincia
A Coruña       True
Alava          True
Almeria        True
Asturias       True
Badajoz        True
Burgos         True
Caceres        True
Cantabria      True
Ceuta          True
Cuenca         True
Formentera     True
Girona         True
Guadalajara    True
Huesca         True
Ibiza          True
Las Palmas     True
Leon           True
Lleida         True
Melilla        True
Menorca        True
Murcia         True
Navarra        True
Ourense        True
Pontevedra     True
Salamanca      True
Segovia        True
Tarragona      True
Teruel         True
Toledo         True
Valencia       True
Valladolid     True
Zamora         True
Name: porcentaje_ocupacion, dtype: bool

In [94]:
national_mean =  data_h['indice_satisfaccion'].mean()
hospitals = data_h[(data_h.groupby(['comunidad_autonoma'])['num_camas'].transform('max') == data_h['num_camas']) ]
hospitals[hospitals['indice_satisfaccion'] < national_mean]['comunidad_autonoma'].unique()

array(['Cantabria', 'Extremadura', 'Comunidad de Madrid',
       'Region de Murcia', 'Pais Vasco', 'La Rioja'], dtype=object)

In [95]:
data_h.loc[
    (data_h['num_camas'] == data_h.groupby('comunidad_autonoma')['num_camas'].transform('max')) &
    (data_h['indice_satisfaccion'] < data_h['indice_satisfaccion'].mean()),
    'comunidad_autonoma'
].unique()

array(['Cantabria', 'Extremadura', 'Comunidad de Madrid',
       'Region de Murcia', 'Pais Vasco', 'La Rioja'], dtype=object)