In [158]:
import requests
import time
import random
import pandas as pd
from pprint import pprint

# Nivell 1
Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.
Exploració bàsica amb una API de laboratori.

### 1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

*    Llista de publicacions (/posts)
*    Llista d’usuaris (/users)
*    Llista de tasques (/todos)

In [159]:
def request_url_method( url, method='get', **kargs ):
    
    answer = None
    try:
        match method:
            case 'get':
                    answer = requests.get( url, params=kargs['params'] )
            case 'post':
                    answer = requests.post( url, json=kargs['json'] )
            case 'patch':
                    answer = requests.patch( url, json=kargs['json'] )
            case 'delete':
                    answer = requests.delete( url )
        
        # No saturar el servidor amb peticions rápides
        wait = 1 + random.uniform( 0, 2 )
        time.sleep( wait )

    except requests.exceptions.RequestException as e:
        print(f" Algo a passat: {e}")
    
    return answer

In [160]:
request_list    = ['posts','users','todos']
request_url     = 'https://jsonplaceholder.typicode.com/'
request_params  = {}

data_url = {}
for item in request_list:
    data_url[item] = request_url_method( request_url + "/" + item, params=request_params )

### 2. Mostra per pantalla:

*    La quantitat total de cada recurs.
*    El codi d'estat de cada petició.

In [161]:
def print_frame_json( json, frame ):

    for line in json[frame['key_data']]:
        for field in frame['key_field']:
            print(f"{field}: {line[field]}")
        print( "-"*60 )

    return None

In [162]:
def print_url_answer( answer, frame={} ):
    
    print(f"El seu codi de estat es: {answer.status_code} ")

    match answer.status_code:
        case 200:
            if 'json' in  answer.headers.get('Content-Type'):
                if not frame:
                    answer_json = answer.json()
                    n_items = len( answer_json )
            
                    if n_items > 1:
                        print(f"Part de la resposta, primer element de {n_items}:")
                        print("-"*60)
                        pprint(answer_json[0])
                    else:
                        print(f"Resposta: \n {answer_json}")
                    print("-"*60)
                
                else:
                    print_frame_json( answer.json(), frame )
            else:
                print(f"\t- De moment només se comptar respostes tipus json ... ")
        case 201:
            print(answer.json())
        case 404:
            print("Aquesta no es la pàgina que hi estas buscant ... ")   
    
    return None

In [163]:
for item, answer in data_url.items():
    print( f"Pel recurs: {item}" )
    print_url_answer( answer )

Pel recurs: posts
El seu codi de estat es: 200
Part de la resposta, primer element de 100:
------------------------------------------------------------
{'body': 'quia et suscipit\n'
         'suscipit recusandae consequuntur expedita et cum\n'
         'reprehenderit molestiae ut ut quas totam\n'
         'nostrum rerum est autem sunt rem eveniet architecto',
 'id': 1,
 'title': 'sunt aut facere repellat provident occaecati excepturi optio '
          'reprehenderit',
 'userId': 1}
------------------------------------------------------------
Pel recurs: users
El seu codi de estat es: 200
Part de la resposta, primer element de 10:
------------------------------------------------------------
{'address': {'city': 'Gwenborough',
             'geo': {'lat': '-37.3159', 'lng': '81.1496'},
             'street': 'Kulas Light',
             'suite': 'Apt. 556',
             'zipcode': '92998-3874'},
 'company': {'bs': 'harness real-time e-markets',
             'catchPhrase': 'Multi-layered client-server neural-net',
             'name': 'Romaguera-Crona'},
 'email': 'Sincere@april.biz',
 'id': 1,
 'name': 'Leanne Graham',
 'phone': '1-770-736-8031 x56442',
 'username': 'Bret',
 'website': 'hildegard.org'}
------------------------------------------------------------
Pel recurs: todos
El seu codi de estat es: 200
Part de la resposta, primer element de 200:
------------------------------------------------------------
{'completed': False, 'id': 1, 'title': 'delectus aut autem', 'userId': 1}
------------------------------------------------------------

### 3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [164]:
recurs_inex = '/fake'
inex_params = {}
data_inex_url   = request_url_method( request_url + recurs_inex, params=inex_params )

In [165]:
print(f"Pel recurs: {recurs_inex}")
print_url_answer( data_inex_url )

Pel recurs: /fake
El seu codi de estat es: 404
Aquesta no es la pàgina que hi estas buscant ...

### 4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

*   Mostra la resposta JSON.
*   Mostra el codi d'estat.

In [166]:
data_post = {
    'userId': 1,
    'title' : 'Lorem ipsum',
    'body'  : 'Lorem ipsum sip inicuanim'
}

url_post = request_url + '/posts'
answer_post = request_url_method( url_post, method='post', json=data_post )

In [167]:
print_url_answer( answer_post )

El seu codi de estat es: 201
{'userId': 1, 'title': 'Lorem ipsum', 'body': 'Lorem ipsum sip inicuanim', 'id': 101}

### 5. Fes una petició PATCH per modificar parcialment una publicació existent.

*   Mostra la resposta JSON.
*   Mostra el codi d'estat.

In [168]:
data_patch={
  'title' : 'ipsum lorem'  
}

url_patch = answer_post.headers['location']
answer_patch = request_url_method( url_patch, method='patch', json=data_patch )

In [169]:
print_url_answer( answer_patch )

El seu codi de estat es: 200
Resposta:
 {'title': 'ipsum lorem'}
------------------------------------------------------------

### 6. Fes una petició DELETE sobre una publicació.

*   Mostra la resposta JSON.
*   Mostra el codi d'estat.

In [170]:
url_delete      = answer_post.headers['location']
answer_delete   = request_url_method( url_delete, method='delete' )

In [171]:
print_url_answer( answer_delete )

El seu codi de estat es: 200
Resposta:
 {}
------------------------------------------------------------

# Nivell 2
Interacció amb una API pública real

### 1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

API escollida "Art Institute of Chicago" "https://api.artic.edu"

### 2. Llegeix la documentació de l'API:

*   Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
*   Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
*   Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

##### EndPoints

*   artworks
*   artists
*   galleries
*   exhibitions
*   artwork-types
*   ...

###### Filtres i parametres:
Generals:
*   `page`      Nombre de la pàgina
*   `limit`     Nombre de recursos per pàgina
*   `fields`    Camps a retornar separats per comes  
*   `ids`       Llista de id's separats per comes

Per artworks:
*   include - Options: artist_pivots, dates, place_pivots, sites

Per .../search:
*   q       - Texte a buscar
*   sort    - Ordenació
*   size    - Nombre de resultats

Els resultats son format Json (per exemple):
```
{
    "data": {
        "id": 4,
        "api_model": "artworks",
        "api_link": "https://api.artic.edu/api/v1/artworks/4",
        "is_boosted": false,
        "title": "Priest and Boy",
        "alt_titles": null,
        ...
    },
    "info": {
        "license_text": "The `description` field in this response is licensed under a Creative Commons Attribution 4.0 Generic License (CC-By) and the Terms and Conditions of artic.edu. All other data in this response is licensed under a Creative Commons Zero (CC0) 1.0 designation and the Terms and Conditions of artic.edu.",
        "license_links": [
            "https://creativecommons.org/publicdomain/zero/1.0/",
            "https://www.artic.edu/terms"
        ],
        "version": "1.14"
    },
    "config": {
        "iiif_url": "https://www-test.artic.edu/iiif/2",
        "website_url": "https://www-test.artic.edu"
    }
}
```

### 3. Fes una petició GET senzilla:

*   Mostra el codi d'estat de la resposta.
*   Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [172]:
API_LINK    = 'https://api.artic.edu/api/v1/'
end_point   = 'artwork-types'
params      = {"limit": 5}
request_url = API_LINK + end_point
answer_api  = request_url_method( request_url, params=params )

In [173]:
frame_api = { 'key_data':'data', 'key_field': ['title', 'api_link'] }
print_url_answer( answer_api, frame= frame_api )

El seu codi de estat es: 200
title: TBM Equipment
api_link: https://api.artic.edu/api/v1/artwork-types/49
------------------------------------------------------------
title: Painting
api_link: https://api.artic.edu/api/v1/artwork-types/1
------------------------------------------------------------
title: Vessel
api_link: https://api.artic.edu/api/v1/artwork-types/23
------------------------------------------------------------
title: Basketry
api_link: https://api.artic.edu/api/v1/artwork-types/22
------------------------------------------------------------
title: Miniature room
api_link: https://api.artic.edu/api/v1/artwork-types/21
------------------------------------------------------------

### 4. Converteix les dades a un DataFrame de pandas:

*   Mostra les primeres files del DataFrame.

In [174]:
df_artwork_types = pd.DataFrame( answer_api.json()[frame_api['key_data']] )
df_artwork_types.head()

,id,api_model,api_link,title,aat_id,source_updated_at,updated_at,timestamp
0,49,artwork-types,https://api.artic.edu/api/v1/artwork-types/49,TBM Equipment,NaN,2026-03-18T16:23:57-05:00,2026-03-18T16:25:22-05:00,2026-06-03T03:08:49-05:00
1,1,artwork-types,https://api.artic.edu/api/v1/artwork-types/1,Painting,300033618.0,2019-05-08T19:03:58-05:00,2022-04-22T10:38:03-05:00,2026-06-03T03:08:49-05:00
2,23,artwork-types,https://api.artic.edu/api/v1/artwork-types/23,Vessel,300193015.0,2019-05-08T19:03:58-05:00,2022-03-15T16:31:40-05:00,2026-06-03T03:08:49-05:00
3,22,artwork-types,https://api.artic.edu/api/v1/artwork-types/22,Basketry,300404578.0,2019-05-08T19:03:58-05:00,2022-03-15T16:31:40-05:00,2026-06-03T03:08:49-05:00
4,21,artwork-types,https://api.artic.edu/api/v1/artwork-types/21,Miniature room,300427608.0,2019-05-08T19:03:59-05:00,2022-03-15T16:31:40-05:00,2026-06-03T03:08:49-05:00

# Nivell 3
API d'Open Data Barcelona

### 1. Utilitza l’API d’Open Data BCN per:

*   Cercar un dataset del teu interès mitjançant package_search i package_show. .

In [175]:
open_url_action = 'https://opendata-ajuntament.barcelona.cat/data/api/action/'
search_action   = 'package_search'
search_param    = {"q": "animales"}

search_data_url = open_url_action  + search_action 
answer_search = request_url_method( search_data_url, params=search_param )

In [176]:
for result in answer_search.json()['result']['results']:
    print( f"Id:{result['id']}"  )
    print( f"Descripciò: {result['notes_translated']['ca']}" )
    print( "-"*60 )

Id:fd362a09-076d-4cea-9965-9ff9b4c257f3
Descripciò: Nombre acumulat a cada districte dels animals de companyia inscrits al Registre censal de la ciutat de Barcelona.
------------------------------------------------------------
Id:e6982c47-dbcf-4c06-a7d9-a9c377c79713
Descripciò: Nombre de gossos i gats gestionats pel Centre d'Acollida d'Animals de Companyia de Barcelona (CAACB). Les dades detallen els recollits de la via pública, els rescatats pel seu propietari i els adoptats.
------------------------------------------------------------
Id:99360f4f-09bb-433a-9450-dddf79d7d2b8
Descripciò: Equipaments de la tipologia Animals i plantes que hi ha a la ciutat de Barcelona: centres de jardineria, veterinaris, floristeries, perruqueries canines, residències d'animals i d'altres.
------------------------------------------------------------
Id:0af3015d-c4da-473c-b0f7-40bc3b5bd4ea
Descripciò: Equipaments de la tipologia Cementiris que hi ha a la ciutat de Barcelona: cementiris públics, cementiris privats, cementiris d'animals, crematoris, tanatoris, sales de vetlla.
------------------------------------------------------------

In [177]:
show_action   = 'package_show'
show_param    = {'id':'99360f4f-09bb-433a-9450-dddf79d7d2b8'}

show_data_url   = open_url_action  + show_action
answer_show     = request_url_method( show_data_url, params=show_param )

In [178]:
resources = []
for resource in answer_show.json()['result']['resources']:
    
    resources.append( {'resource_id':resource['id'], 'format': resource['format'], 'created': resource['created'] })

print( *resources, sep='\n' )

{'resource_id': '0b57a185-8986-4d0f-922f-da8415056575', 'format': 'CSV', 'created': '2021-06-10T11:18:53.225364'}
{'resource_id': '80db965a-72b3-468d-b481-61a3105a4c2e', 'format': 'JSON', 'created': '2021-03-24T20:43:51.033356'}

### 2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [179]:
print( resources[0] )

{'resource_id': '0b57a185-8986-4d0f-922f-da8415056575', 'format': 'CSV', 'created': '2021-06-10T11:18:53.225364'}

### 3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

*   Recuperar almenys 100 registres.

In [180]:
datastore_action = 'datastore_search'
datastore_param  = {'resource_id':resources[0]['resource_id'], 'limit':100}
datastore_url    = open_url_action  + datastore_action

answer_datastore = request_url_method( datastore_url, params=datastore_param )
datasore_json    = answer_datastore.json()

In [181]:
print( f"N'hi ha 100 registres a la resposta?: {len( datasore_json['result']['records'] ) == 100}" )

N'hi ha 100 registres a la resposta?: True

### 4. Converteix els resultats a un DataFrame.

In [182]:
df_equipaments = pd.DataFrame( datasore_json['result']['records'] )
df_equipaments.head()

,addresses_roadtype_name,addresses_end_street_number,geo_epgs_4326_lon,values_attribute_name,estimated_dates,addresses_road_name,values_category,addresses_zip_code,secondary_filters_id,values_value,...,institution_name,modified,secondary_filters_asia_id,secondary_filters_fullpath,geo_epgs_4326_lat,values_description,values_id,addresses_neighborhood_name,values_outstanding,values_attribute_id
0,,61,2.1466644269033046,Tel.,,Carrer de Laforja,Telèfons,8021,None,671157673,...,,2024-06-10T11:42:18.857657,None,,41.39716394444067,,233424,Sant Gervasi - Galvany,True,20001
1,,NaN,2.1198884386188213,Tel.,,C Major de Sarrià,Telèfons,8017,None,932053116,...,,2023-10-03T10:43:07.588542,None,,41.40183589113448,,140721,Sarrià,True,20001
2,,NaN,2.1296659137585396,Tel.,,Fígols,Telèfons,8028,None,933309762,...,,2023-10-03T10:44:33.234395,None,,41.38271945689916,,137984,les Corts,True,20001
3,,NaN,2.1110624879700417,Centraleta,,Carrer dels Cavallers,Telèfons,8034,None,932858400,...,,2026-04-30T14:03:32.352064,None,,41.390276839970724,,136514,Pedralbes,True,20003
4,,NaN,2.163378925460572,Tel.,,C Margarit,Telèfons,8004,None,934424854,...,,2016-03-21T17:09:09,None,,41.3733002204874,,224660,el Poble-sec,True,20001

### 5. Desa el DataFrame en un fitxer .csv.

In [183]:
try:
    df_equipaments.to_csv( './equipaments.csv', sep=';', encoding='utf-8-sig', na_rep='NULL', index=False )
except Exception:
    print( "Algo a passat: {e}" )